# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: self-hosted

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm i -g pm2

    - name: Create .env
      run: |
        touch .env
        echo "${{ secrets.DEVSHARE_PROD }}" > .env

    - run: npm run build

    - name: Start or Restart PM2 + Redis
      run: |
        if pm2 describe DevShare > /dev/null; then
          echo "DevShare is running → restarting..."
          pm2 restart DevShare
        else
          echo "DevShare not found → starting Redis + new PM2 instance..."

          # Start Redis container if not running
          if ! docker ps --format '{{.Names}}' | grep -q "^redis$"; then
            echo "Starting Redis container..."
            docker run -d \
              --name redis \
              -p 6379:6379 \
              redis:latest
          else
            echo "Redis is already running."
          fi

          # Start DevShare instance
          pm2 start dist/index.js --name DevShare
        fi
